const express=require('express');
const router=express.Router();
const authAdmin = require('../middlewares/authadmin.js');
const {SignIn,SignUp}=require('../controllers/adminController.js');
const {courses,createcourse,deleteCourse} = require('../controllers/courseController.js');
router.post('/signin',SignIn);
router.post('/signup',SignUp);
router.post('/createcourse',authAdmin,createcourse);
router.delete('/delete/course', authAdmin, deleteCourse);
router.get('/courses',authAdmin, courses);
module.exports=router;
